"""Add grades and skills

Revision ID: 1d6cd1435ba1
Revises: 0001_initial_schema
Create Date: 2026-02-18 11:31:59.744280

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d6cd1435ba1"
down_revision: str | None = "0001_initial_schema"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "grades",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sequence_order", sa.Integer(), nullable=False),
        sa.Column("school_id", sa.Uuid(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_grades_school_id"), "grades", ["school_id"], unique=False)
    op.create_table(
        "rider_grade_history",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("rider_id", sa.Uuid(), nullable=False),
        sa.Column("grade_id", sa.Uuid(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("school_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["grade_id"],
            ["grades.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rider_id"],
            ["rider_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rider_grade_history_grade_id"),
        "rider_grade_history",
        ["grade_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rider_grade_history_rider_id"),
        "rider_grade_history",
        ["rider_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rider_grade_history_school_id"),
        "rider_grade_history",
        ["school_id"],
        unique=False,
    )
    op.create_table(
        "skills",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("grade_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("school_id", sa.Uuid(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["grade_id"],
            ["grades.id"],
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_skills_grade_id"), "skills", ["grade_id"], unique=False)
    op.create_index(op.f("ix_skills_school_id"), "skills", ["school_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_skills_school_id"), table_name="skills")
    op.drop_index(op.f("ix_skills_grade_id"), table_name="skills")
    op.drop_table("skills")
    op.drop_index(
        op.f("ix_rider_grade_history_school_id"), table_name="rider_grade_history"
    )
    op.drop_index(
        op.f("ix_rider_grade_history_rider_id"), table_name="rider_grade_history"
    )
    op.drop_index(
        op.f("ix_rider_grade_history_grade_id"), table_name="rider_grade_history"
    )
    op.drop_table("rider_grade_history")
    op.drop_index(op.f("ix_grades_school_id"), table_name="grades")
    op.drop_table("grades")
    # ### end Alembic commands ###
