"""Add permissions

Revision ID: f66f0169a4d4
Revises:
Create Date: 2026-02-15 13:57:57.686745

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f66f0169a4d4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # op.create_table(
    #     "roles",
    #     sa.Column("id", sa.Integer(), nullable=False),
    #     sa.Column("name", sa.String(), nullable=False),
    #     sa.Column("description", sa.String(), nullable=True),
    #     sa.PrimaryKeyConstraint("id"),
    #     sa.UniqueConstraint("name"),
    # )
    # op.create_table(
    #     "schools",
    #     sa.Column("id", sa.Uuid(), nullable=False),
    #     sa.Column("name", sa.String(), nullable=True),
    #     sa.Column("slug", sa.String(), nullable=True),
    #     sa.Column(
    #         "created_at",
    #         sa.DateTime(timezone=True),
    #         server_default=sa.text("(CURRENT_TIMESTAMP)"),
    #         nullable=True,
    #     ),
    #     sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    #     sa.PrimaryKeyConstraint("id"),
    # )
    # op.create_index(op.f("ix_schools_name"), "schools", ["name"], unique=False)
    # op.create_index(op.f("ix_schools_slug"), "schools", ["slug"], unique=True)
    # op.create_table(
    #     "users",
    #     sa.Column("id", sa.Uuid(), nullable=False),
    #     sa.Column("email", sa.String(), nullable=True),
    #     sa.Column("hashed_password", sa.String(), nullable=True),
    #     sa.Column("first_name", sa.String(), nullable=False),
    #     sa.Column("last_name", sa.String(), nullable=False),
    #     sa.Column("is_active", sa.Boolean(), nullable=True),
    #     sa.Column("is_superuser", sa.Boolean(), nullable=True),
    #     sa.Column(
    #         "created_at",
    #         sa.DateTime(timezone=True),
    #         server_default=sa.text("(CURRENT_TIMESTAMP)"),
    #         nullable=True,
    #     ),
    #     sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    #     sa.PrimaryKeyConstraint("id"),
    # )
    # op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # op.create_table(
    #     "memberships",
    #     sa.Column("id", sa.Uuid(), nullable=False),
    #     sa.Column("user_id", sa.Uuid(), nullable=False),
    #     sa.Column("school_id", sa.Uuid(), nullable=False),
    #     sa.Column(
    #         "created_at",
    #         sa.DateTime(timezone=True),
    #         server_default=sa.text("(CURRENT_TIMESTAMP)"),
    #         nullable=True,
    #     ),
    #     sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    #     sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    #     sa.ForeignKeyConstraint(
    #         ["school_id"],
    #         ["schools.id"],
    #     ),
    #     sa.ForeignKeyConstraint(
    #         ["user_id"],
    #         ["users.id"],
    #     ),
    #     sa.PrimaryKeyConstraint("id"),
    #     sa.UniqueConstraint("user_id", "school_id", name="uq_user_school"),
    # )
    # op.create_index(
    #     op.f("ix_memberships_school_id"), "memberships", ["school_id"], unique=False
    # )
    # op.create_index(
    #     op.f("ix_memberships_user_id"), "memberships", ["user_id"], unique=False
    # )
    # op.create_table(
    #     "rider_profiles",
    #     sa.Column("id", sa.Uuid(), nullable=False),
    #     sa.Column("user_id", sa.Uuid(), nullable=False),
    #     sa.Column("school_id", sa.Uuid(), nullable=False),
    #     sa.Column("height_cm", sa.Float(), nullable=True),
    #     sa.Column("weight_kg", sa.Float(), nullable=True),
    #     sa.Column("date_of_birth", sa.Date(), nullable=True),
    #     sa.Column(
    #         "created_at",
    #         sa.DateTime(timezone=True),
    #         server_default=sa.text("(CURRENT_TIMESTAMP)"),
    #         nullable=True,
    #     ),
    #     sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    #     sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    #     sa.ForeignKeyConstraint(
    #         ["school_id"],
    #         ["schools.id"],
    #     ),
    #     sa.ForeignKeyConstraint(
    #         ["user_id"],
    #         ["users.id"],
    #     ),
    #     sa.PrimaryKeyConstraint("id"),
    # )
    # op.create_index(
    #     op.f("ix_rider_profiles_school_id"),
    #     "rider_profiles",
    #     ["school_id"],
    #     unique=False,
    # )
    # op.create_index(
    #     op.f("ix_rider_profiles_user_id"), "rider_profiles", ["user_id"], unique=False
    # )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    # op.create_table(
    #     "membership_roles",
    #     sa.Column("membership_id", sa.Uuid(), nullable=False),
    #     sa.Column("role_id", sa.Integer(), nullable=False),
    #     sa.ForeignKeyConstraint(
    #         ["membership_id"],
    #         ["memberships.id"],
    #     ),
    #     sa.ForeignKeyConstraint(
    #         ["role_id"],
    #         ["roles.id"],
    #     ),
    #     sa.PrimaryKeyConstraint("membership_id", "role_id"),
    # )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table("membership_roles")
    op.drop_table("role_permissions")
    # op.drop_index(op.f("ix_rider_profiles_user_id"), table_name="rider_profiles")
    # op.drop_index(op.f("ix_rider_profiles_school_id"), table_name="rider_profiles")
    # op.drop_table("rider_profiles")
    # op.drop_index(op.f("ix_memberships_user_id"), table_name="memberships")
    # op.drop_index(op.f("ix_memberships_school_id"), table_name="memberships")
    # op.drop_table("memberships")
    # op.drop_index(op.f("ix_users_email"), table_name="users")
    # op.drop_table("users")
    # op.drop_index(op.f("ix_schools_slug"), table_name="schools")
    # op.drop_index(op.f("ix_schools_name"), table_name="schools")
    # op.drop_table("schools")
    # op.drop_table("roles")
    op.drop_table("permissions")
    # ### end Alembic commands ###
